version: '3'
services:
  overlay-example:
    image: daunnc/openjdk-gdal:2.3.2
    command: /bin/sh -c "java -cp /opt/geotrellis-server-example.jar geotrellis.server.example.overlay.WeightedOverlayServer"
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
      - ./example/target/scala-2.11/geotrellis-server-example.jar:/opt/geotrellis-server-example.jar
  persistence-example:
    image: daunnc/openjdk-gdal:2.3.2
    command: /bin/sh -c "java -cp /opt/geotrellis-server-example.jar geotrellis.server.example.persistence.PersistenceServer"
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
      - ./example/target/scala-2.11/geotrellis-server-example.jar:/opt/geotrellis-server-example.jar
  ndvi-example:
    image: daunnc/openjdk-gdal:2.3.2
    command: /bin/sh -c "java -cp /opt/geotrellis-server-example.jar geotrellis.server.example.ndvi.NdviServer"
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
      - ./example/target/scala-2.11/geotrellis-server-example.jar:/opt/geotrellis-server-example.jar
  gdal-ndvi-example:
    image: daunnc/openjdk-gdal:2.3.2
    command: /bin/sh -c "java -Djava.library.path=/usr/local/lib -cp /opt/geotrellis-server-example.jar geotrellis.server.example.ndvi.GdalNdviServer"
    ports:
      - "9000:9000"
    volumes:
      - $HOME/.aws:/root/.aws
      - ./example/target/scala-2.11/geotrellis-server-example.jar:/opt/geotrellis-server-example.jar
  server-microsite:
    image: quay.io/geotrellis/server-microsite:latest
    command: bash -c "cd /root/geotrellis-server/docs/target/site && jekyll serve --host 0.0.0.0"
    ports:
      - "4000:4000"
    volumes:
      - $HOME/.sbt:/root/.sbt
      - $HOME/.ivy2:/root/.ivy2
      - ./:/root/geotrellis-server
    build:
      dockerfile: microsite.dockerfile
      context: .
  ogc-example:
    image: daunnc/openjdk-gdal:2.3.2
    command: /bin/sh -c "AWS_PROFILE=azavea-rd java -Djava.library.path=/usr/local/lib -jar /opt/jars/geotrellis-server-ogc-services.jar --public-url http://localhost:9999"
    ports:
      - "9999:9000"
    volumes:
      - $HOME/.aws:/root/.aws
      - ./ogc-example/target/scala-2.11:/opt/jars
      - ./data:/opt/data
