addDependencyTreePlugin
addSbtPlugin("com.eed3si9n"       % "sbt-assembly" % "1.0.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"  % "0.5.3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.3.7")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"   % "0.4.3")
addSbtPlugin("org.scalaxb"        % "sbt-scalaxb"  % "1.8.1")
addSbtPlugin("se.marcuslonnberg"  % "sbt-docker"   % "1.5.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype" % "2.5")
addSbtPlugin("io.crashbox"        % "sbt-gpg"      % "0.2.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-git"      % "1.0.0")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"   % "5.5.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix" % "0.9.29")
