#!/bin/bash

set -e

if [[ -n "${GEOTRELLIS_SERVER_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Execute tests.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        ./scripts/test
    fi
fi
