#!/bin/bash

set -e

if [[ -n "${GEOTRELLIS_SERVER_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Publish artifacts.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        echo "Publishing artifacts to Sonatype"
        if [[ -n "${CIRCLE_TAG}" ]]; then
            ./sbt ";++${SCALA_VERSION};compile;sonatypeOpen ${CIRCLE_BUILD_NUM};publish;sonatypeRelease"
        else
            ./sbt ";++${SCALA_VERSION};compile;publish"
        fi

        echo "Publishing artifacts to quay.io"
        docker login -u "${QUAY_USER}" -p "${QUAY_PASSWORD}" quay.io
        docker tag "geotrellis-server-stac:${GIT_COMMIT}" "quay.io/geotrellis/geotrellis-server-stac:${GIT_COMMIT}"
        docker push "quay.io/geotrellis/geotrellis-server-stac:${GIT_COMMIT}"
        if [[ "${CIRCLE_BRANCH}" =~ ^main$ ]]; then
            docker tag "geotrellis:${GIT_COMMIT}" "quay.io/geotrellis/geotrellis-server-stac:latest"
            docker push "quay.io/geotrellis/geotrellis-server-stac:latest"
        fi
    fi
fi
